import Testing
@testable import mStatsKit

@Suite struct ClipboardPrivacyTests {
    @Test func allowsNormalTextTypes() {
        #expect(ClipboardPrivacy.shouldSkip(types: ["public.utf8-plain-text"]) == false)
    }

    @Test func skipsConcealedType() {
        #expect(ClipboardPrivacy.shouldSkip(types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]) == true)
    }

    @Test func skipsTransientType() {
        #expect(ClipboardPrivacy.shouldSkip(types: ["public.utf8-plain-text", "org.nspasteboard.TransientType"]) == true)
    }

    @Test func skipsAutoGeneratedType() {
        #expect(ClipboardPrivacy.shouldSkip(types: ["public.utf8-plain-text", "org.nspasteboard.AutoGeneratedType"]) == true)
    }

    @Test func allowsEmptyTypesList() {
        #expect(ClipboardPrivacy.shouldSkip(types: []) == false)
    }
}
