import Foundation

/// Whether a pasteboard change should be skipped, per the nspasteboard.org
/// convention several password managers and other "don't record me" apps
/// already use: if any of these marker types are present alongside the
/// string content, a clipboard-history tool should not record it. Takes
/// raw type identifiers (not `NSPasteboard.PasteboardType`) so this stays
/// pure/testable without constructing pasteboard state.
public enum ClipboardPrivacy {
    public static let markerTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    public static func shouldSkip(types: [String]) -> Bool {
        !markerTypes.isDisjoint(with: types)
    }
}
